model:
  channel_in_list: [1,8,16]
  channel_out_list: [8, 16, 32]
  linear_in_features: 100

data:
  path: 
    train: ./data/train_ds_tf
    eval: ./data/eval_ds_tf
    grid: ./data/start_grid_64x64.mat
  batch_size: 512
  shuffle: true

train:
  epochs: 400 #2800
  print_every_epoch: 1
  optimizer: 'Adam'
  lr: 
    scheduler:
      init_args:
        decay_rate: 0.75
        decay_steps: 70000
        initial_learning_rate: 0.001
  Gauss_filt_dim: 3
  is_physics_informed: True #True
  from_ckpt: True
  ckpt_path: ./ckpt/
  logging:
    wandb: 
      project: debugging
  trained_model:
    dir: './trained_models/'
    name: 'PlaNet_70ksample_no_physics_informed/'

eval:





