model:
  channel_in_list: [1,8,16]
  channel_out_list: [8, 16, 32]
  linear_in_features: 100

data:
  path: 
    # train: ./data/tf_Dataset_train_NeuralOpt_64x64_10000_samples.data
    train: ./data/tf_Dataset_train_NeuralOpt_64x64_70000_samples.data
    test: ./data/tf_Dataset_test_NeuralOpt_64x64_16398_samples.data
  batch_size: 64
  shuffle: true

train:
  epochs: 100
  print_every_epoch: 1
  is_physics_informed: False
  ckpt_path: ./ckpt/




