data:
  batch_size: 64
  path:
    grid: ./data/data_geo_Dataset_NeuralOpt_super_res_64x64.mat
    test: ./data/tf_Dataset_test_NeuralOpt_64x64_16398_samples.data
    train: ./data/tf_Dataset_train_NeuralOpt_64x64_10000_samples.data
  shuffle: true
eval: null
model:
  channel_in_list:
  - 1
  - 8
  - 16
  channel_out_list:
  - 8
  - 16
  - 32
  linear_in_features: 100
train:
  Gauss_filt_dim: 3
  ckpt_path: ./ckpt/
  epochs: 400
  from_ckpt: true
  is_physics_informed: true
  logging:
    wandb:
      project: PlaNet_physics_informed
  lr:
    scheduler:
      init_args:
        decay_rate: 0.5
        decay_steps: 65000
        initial_learning_rate: 0.001
  print_every_epoch: 1
  trained_model:
    dir: ./trained_models/
    name: PlaNet_physics_informed/
